### ISSUE TITLE
mobile first?

### ISSUE THREAD

**Issue by FrancisA2000** [FACN8/HelloAtlas#21]
its not a perfect mobile first design 
and not very accessible

![Annotation 2020-01-23 102400](https://user-images.githubusercontent.com/57587852/72967673-873f9280-3dca-11ea-881a-58faccc3c5a3.png)
  
![Annotation 2020-01-23 102542](https://user-images.githubusercontent.com/57587852/72967815-d980b380-3dca-11ea-87d6-40a86fdc62f3.png)

**Comment by Rabeaf** [comment]
Fixed
